#!/usr/bin/env bash
#
# Generates a lane-grouped index (group + test name + labels + source)
# of every Ginkgo `It(...)` spec in test/e2e, via `ginkgo --dry-run`.
# Use this to cross-check Lane/Label/Test/File alignment in
# e2e-test-summary.md; it cannot produce prerequisites/steps/pass-check
# columns, which stay hand-maintained.
#
# Usage:
#   test/e2e/scripts/gen-spec-index.sh                           # print to stdout
#   test/e2e/scripts/gen-spec-index.sh > OUT.md                  # write to file
#   test/e2e/scripts/gen-spec-index.sh --label-filter 'smoke'    # subset by label expression
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  test/e2e/scripts/gen-spec-index.sh [--label-filter '<expr>']
  test/e2e/scripts/gen-spec-index.sh --help
EOF
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: required command not found: $cmd" >&2
    exit 1
  fi
}

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TESTDIR="$(cd "$HERE/.." && pwd)"
REPORT="$(mktemp -t e2e-spec-report.XXXXXX.json)"
trap 'rm -f "$REPORT"' EXIT

LABEL_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --label-filter)
      if [[ $# -lt 2 || -z "${2:-}" ]]; then
        echo "error: --label-filter requires a non-empty value" >&2
        usage >&2
        exit 1
      fi
      LABEL_FILTER="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_cmd go
require_cmd jq

GINKGO_ARGS=(--dry-run "--json-report=$REPORT" --no-color)
if [[ -n "$LABEL_FILTER" ]]; then
  GINKGO_ARGS+=(--label-filter "$LABEL_FILTER")
fi

if ! (
  cd "$TESTDIR"
  go run github.com/onsi/ginkgo/v2/ginkgo "${GINKGO_ARGS[@]}" >/dev/null
); then
  cat >&2 <<'EOF'
error: failed to generate dry-run Ginkgo JSON report.
hint: verify dependencies and suite compilation with:
  go test ./test/e2e/...
EOF
  exit 1
fi

jq -e -r --arg label_filter "$LABEL_FILTER" '
  def known_lanes:
    ["smoke", "operator", "features", "auth", "bootc", "internal-registry",
     "package-mode", "container-build", "manifest-validation", "catalog"];

  # flatten container + leaf labels and drop the ordering-only "Serial" tag
  def labels:
    ((.ContainerHierarchyLabels + [.LeafNodeLabels])
      | flatten
      | unique
      | map(select(. != "Serial")));

  def lane_labels:
    labels
    | map(select(. as $label | (known_lanes | index($label)) != null));

  # when a test has both "smoke" and a more specific lane label,
  # classify by the specific lane for cleaner grouping.
  def lane:
    (lane_labels - ["smoke"]) as $non_smoke
    | if ($non_smoke | length) > 0 then
        ($non_smoke | sort | first)
      elif (lane_labels | length) > 0 then
        (lane_labels | sort | first)
      else
        (labels | if length > 0 then (sort | first) else "unlabeled" end)
      end;

  def group:
    (.ContainerHierarchyTexts
      | map(select(. != ""))
      | join(" > "));

  def rel_file:
    (.LeafNodeLocation.FileName | sub("^.*/test/e2e/"; ""));

  def source:
    rel_file + ":" + (.LeafNodeLocation.LineNumber | tostring);

  def esc_md:
    tostring
    | gsub("\\|"; "\\\\|")
    | gsub("\n"; " ");

  "# E2E Spec Index",
  "",
  "> Auto-generated by `test/e2e/scripts/gen-spec-index.sh` — do not edit by hand.",
  "> Regenerate after adding/renaming/removing `It(...)` specs or `Label(...)` lanes.",
  "> For dual-labeled specs (for example `operator` + `smoke`), grouping prefers the non-`smoke` label.",
  (if $label_filter != "" then "> Label filter: `" + ($label_filter | esc_md) + "`." else empty end),
  "",
  (
    [ .[]?.SpecReports[]?
      | select(.LeafNodeType == "It")
      | select($label_filter == "" or .State != "skipped")
      | {
          lane: lane,
          group: group,
          labels: (labels | sort | join(", ")),
          name: .LeafNodeText,
          source: source,
          source_file: rel_file,
          source_line: .LeafNodeLocation.LineNumber
        }
    ] as $specs
    | if ($specs | length) == 0 then
        "_No `It(...)` specs found in the dry-run report._",
        ""
      else
        (
          $specs
          | sort_by(.lane, .group, .source_file, .source_line, .name)
          | group_by(.lane)
          | sort_by((.[0].lane as $lane | (known_lanes | index($lane) // 999)), .[0].lane)
          | .[]
          | (
              "## Lane: `" + .[0].lane + "` (" + (length | tostring) + " specs)",
              "",
              "| Group | Test Name | Labels | Source |",
              "|---|---|---|---|",
              (
                .[]
                | "| "
                  + (.group | esc_md)
                  + " | "
                  + (.name | esc_md)
                  + " | `"
                  + (.labels | esc_md)
                  + "` | `"
                  + .source
                  + "` |"
              ),
              ""
            )
        )
      end
  )
' "$REPORT"
